# Generated by Django 6.0 on 2026-02-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='require_registered_voters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
