# Generated by Django 6.0 on 2026-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_election_end_date_election_require_registered_voters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='election',
            name='start_date',
        ),
        migrations.AddField(
            model_name='election',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
